import "./Building/BuildingOperateSystem";
import "./Building/BuildingStateSystem";
import "./Input/ProcessMessageSystem"
import "./Work/WorkOperateSystem";
import "./Work/WorkProgressUpdateSystem";
import "./Work/RestOperateSystem";
import "./Work/RestProgressUpdateSystem";
import "./Monster/MonsterOperateSystem";
import "./Space/SpaceChangeSystem";